### ISSUE TITLE
Crash when you deleted a torrent

### ISSUE THREAD

**Issue by abunasar** [Mrigank11/embetacloud#39]
The app crashes when you delete a torrent from web interface:

> upload-to-gdrive@1.0.0 start /root/embetacloud
> node server/server.js

Server Started
/root/embetacloud/server/server.js:206
        torrents[uniqid].uploadTo.forEach(function (sessionId) {
                        ^

TypeError: Cannot read property 'uploadTo' of undefined
    at Torrent.<anonymous> (/root/embetacloud/server/server.js:206:25)
    at emitOne (events.js:77:13)
    at Torrent.emit (events.js:169:7)
    at EventEmitter.<anonymous> (/root/embetacloud/server/Torrent/Torrent.js:70:19)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)
    at gc (/root/embetacloud/node_modules/torrent-stream/index.js:217:44)
    at onpiececomplete (/root/embetacloud/node_modules/torrent-stream/index.js:233:7)
    at null.callback (/root/embetacloud/node_modules/torrent-stream/index.js:332:9)
    at Wire._callback (/root/embetacloud/node_modules/peer-wire-protocol/index.js:315:10)
    at Wire._onpiece (/root/embetacloud/node_modules/peer-wire-protocol/index.js:294:7)

npm ERR! Linux 4.13.0-1011-gcp
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! upload-to-gdrive@1.0.0 start: `node server/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the upload-to-gdrive@1.0.0 start script 'node server/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the upload-to-gdrive package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs upload-to-gdrive
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls upload-to-gdrive
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/embetacloud/npm-debug.log

**Comment by abunasar** [comment]
more errors when you add a torrent via url:

`root@instance-1:~/embetacloud# npm start

> upload-to-gdrive@1.0.0 start /root/embetacloud
> node server/server.js

Server Started
/root/embetacloud/server/server.js:520
                        convert: function (x) { return x.match(/Size (.*),/)[1]; }
                                                                            ^

TypeError: Cannot read property '1' of null
    at Object.scrapeIt.result.data.size.convert (/root/embetacloud/server/server.js:520:77)
    at /root/embetacloud/node_modules/scrape-it/lib/index.js:180:38
    at iterateObject (/root/embetacloud/node_modules/iterate-object/lib/index.js:25:17)
    at handleDataObj (/root/embetacloud/node_modules/scrape-it/lib/index.js:130:9)
    at /root/embetacloud/node_modules/scrape-it/lib/index.js:155:32
    at iterateObject (/root/embetacloud/node_modules/iterate-object/lib/index.js:25:17)
    at handleDataObj (/root/embetacloud/node_modules/scrape-it/lib/index.js:130:9)
    at Function.scrapeIt.scrapeHTML (/root/embetacloud/node_modules/scrape-it/lib/index.js:190:12)
    at /root/embetacloud/node_modules/scrape-it/lib/index.js:29:27
    at /root/embetacloud/node_modules/cheerio-req/lib/index.js:24:9

npm ERR! Linux 4.13.0-1011-gcp
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! upload-to-gdrive@1.0.0 start: `node server/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the upload-to-gdrive@1.0.0 start script 'node server/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the upload-to-gdrive package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs upload-to-gdrive
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls upload-to-gdrive
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/embetacloud/npm-debug.log
`

**Comment by Mrigank11** [comment]
I'm not able to reproduce any of them. Could you tell me how to reproduce them?
